# Generated by Django 3.1 on 2020-10-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_on']},
        ),
    ]
